export let devicon = {
    "android":      "/devicon/android-original.svg",
    "angular":      "/devicon/angularjs-original.svg",
    "arduino":      "/devicon/arduino-original.svg",
    "bootstrap":    "/devicon/bootstrap-original.svg",
    "c":            "/devicon/c-original.svg",
    "c++":          "/devicon/cplusplus-original.svg",
    "c#":           "/devicon/csharp-original.svg",
    "css":          "/devicon/css3-original-wordmark.svg",
    "django":       "/devicon/django-original.svg",
    "docker":       "/devicon/docker-original.svg",
    ".net":         "/devicon/dot-net-original.svg",
    ".net core":    "/devicon/dotnetcore-original.svg",
    "electron":     "/devicon/electron-original.svg",
    "firebase":     "/devicon/firebase-original.svg",
    "flask":        "/devicon/flask-original.svg",
    "flutter":      "/devicon/flutter-original.svg",
    "gatsby":       "/devicon/gatsby-original.svg",
    "gimp":         "/devicon/gimp-original.svg",
    "git":          "/devicon/git-original.svg",
    "github":       "/devicon/github-original.svg",
    "go":           "/devicon/go-original.svg",
    "godot":        "/devicon/godot-original.svg",
    "google cloud": "/devicon/googlecloud-original.svg",
    "graphql":      "/devicon/graphql-original.svg",
    "heroku":       "/devicon/heroku-original.svg",
    "html":         "/devicon/html5-original-wordmark.svg",
    "java":         "/devicon/java-original.svg",
    "javascript":   "/devicon/javascript-original.svg",
    "jira":         "/devicon/jira-original.svg",
    "jquery":       "/devicon/jquery-original.svg",
    "kotlin":       "/devicon/kotlin-original.svg",
    "laravel":      "/devicon/laravel-original.svg",
    "less":         "/devicon/less-plain-wordmark.svg",
    "markdown":     "/devicon/markdown-original.svg",
    "materialui":   "/devicon/materialui-original.svg",
    "mongodb":      "/devicon/mongodb-original.svg",
    "mysql":        "/devicon/mysql-original.svg",
    "nextjs":       "/devicon/nextjs-original.svg",
    "nodejs":       "/devicon/nodejs-original.svg",
    "npm":          "/devicon/npm-original-wordmark.svg",
    "php":          "/devicon/php-original.svg",
    "postgresql":   "/devicon/postgresql-original.svg",
    "python":       "/devicon/python-original.svg",
    "ruby on rails":"/devicon/rails-original-wordmark.svg",
    "raspberry pi": "/devicon/raspberrypi-original.svg",
    "react":        "/devicon/react-original.svg",
    "redux":        "/devicon/redux-original.svg",
    "ruby":         "/devicon/ruby-original.svg",
    "sass":         "/devicon/sass-original.svg",
    "swift":        "/devicon/swift-original.svg",
    "tailwind":     "/devicon/tailwindcss-plain.svg",
    "tensorflow":   "/devicon/tensorflow-original.svg",
    "typescript":   "/devicon/typescript-original.svg",
    "vuejs":        "/devicon/vuejs-original.svg",
    "webpack":      "/devicon/webpack-original.svg",
    "yarn":         "/devicon/yarn-original.svg",
}